database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application_port: 8000
application_ip: "127.0.0.1"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
